### ISSUE TITLE
link to IRC webchat

### ISSUE THREAD

**Issue by kumavis** [voxel/voxeljs-site#10]
I noticed there was no mention of the irc channel on the webbypage (i think)

Not sure if we want this or not, but here is a link to a webchat version of #voxel.js

`http://webchat.freenode.net/?randomnick=1&channels=voxel.js`

or for those with proper native clients, this usually works

`<a href="irc://irc.freenode.net:6667/voxel.js">internets</a>`

**Comment by deathcap** [comment]
Added in https://github.com/voxel/voxeljs.com/pull/15
