### ISSUE TITLE
Project directory where/how?

### ISSUE THREAD

**Issue by 0joshuaolson1** [voxel/voxeljs-site#13]
"Once node.js is installed, you can install the basic voxel.js npm package in your project directory, and then install a basic texture pack. Make a file called package.json in your project directory and give it these contents:"

This doesn't explain where project directories go. Do they have to be inside the top node_modules folder? Do we have to change a PATH variable?

**Comment by max-mapper** [comment]
an example of a project directory is a new empty folder that you create anywhere you want.

e.g.

```
cd /Users/bob
mkdir foo
cd foo
```
